### Good request
POST http://localhost:8000/vm/start

{
    "cpu_count": 4,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}

### Stop (change ID)
POST http://localhost:8000/vm/83ef5a12c0cc41e1bddbb395e8bef5f6/stop

### CPU count too high
POST http://localhost:8000/vm/start

{
    "cpu_count": 400,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}