### Good request
POST http://localhost:8000/vm/start

{
    "cpu_count": 4,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}

### Stop (change ID)
POST http://localhost:8000/vm/ce0dfa540135448681508757aa8f27c1/stop

### CPU count too high
POST http://localhost:8000/vm/start

{
    "cpu_count": 400,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}